### ISSUE TITLE
Increasing message interval for over 2 minutes - hangs in DoWork function

### ISSUE THREAD

**Issue by ellainec** [Avnet/azure-iot-mbed-client#6]
Hi,

I'm using this Avnet's Telus LTE-M IoT Starter Kit with the sample code provided by this repo, but I'm running into an issue where when I sleep the thread for anything over a minute it stops sending. It sends the first time, but when the loop runs again it calls DoWork and never leaves, it just hangs there. I tried asking this question over at [azure-io-sdk-c](https://github.com/Azure/azure-iot-sdk-c/issues/1323)'s repo but they suggested that I ask here instead since there are runtime/platform specifics that they aren't familiar with.

This happens when I don't change anything in the main .cpp file except for value inside ThisThread::sleep_for() 
I've also tried putting the BG96 module to PSM while the thread is sleeping, and it's the same result (hangs in DoWork). 

My goal is to lower the power consumption so that the device lasts for ~1 week before it runs out of battery (battery pack I'm using is 6700mAh) and I have flexibility on how often a message is sent. Any advice/guidance would be appreciated.
Thank you!
Ellaine

**Comment by ghost** [comment]
Hi Ellaine, here is the problem you are hitting:
1. Once you connect to Azure, the system maintains the connection with keep-alive messages periodically.  I am not sure the frequency or architecture of Microsofts solution, but what you are doing is:
a. connect to azure
b. sending info and getting responses
c. turning off the receiver so you can receive no further messages form azure until you turn it on again
d. meanwhile, azure is pinging you system to make sure it is still connected.  But it doesn't get any responses so it assumes it is no longer accessible and takes down the connection.
e. you power the system back up, and you think you have a connection to azure and start trying to talk with it.  But the system has been taken down from the cloud side due to a lack of response
f. I'm not sure how they handle that use case but from your description, it doesn't sound like it is handled very gracefully--it simply crashes

So the problem is that you are disabling your receiver while on an active connection and thus causing azure to disconnect.

To fix this problem, you have to take down the azure connection prior to turning off the radio or entering PSM.  Basically, you have to call  'IoTHubClient_LL_Destroy(iotHubClientHandle)' prior to powering down the device then have to setup the IoT client when you power on the system.  I'm not sure the exact sequence of events needed but tearing down the channel when powering down, and setting it up when powering it back up is what you will have to do.  You could ask MSFT on their github page if they have an API call to power down/up a connection which would make it a cleaner implementation, but I don't know if they do or not.  The blunt force method that would work would be to take down the connection then reestablish one when powering up.  They you need to determine what the minimum sleep time needed is to make the power-savings a positive attribute for the system (e.g., I don't know how much power it takes to bring the IoT link up/down but you need to save at least that much to make it worth while.

Sorry I don't have any implementation example, but with the info above you should be able to implement what you are attempting.

/Jim

**Comment by ellainec** [comment]
This was really helpful - thank you so much!
